/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:cf1f17be-1107-4b4d-9294-286de114326b",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_99ZveVbRA",
    "aws_user_pools_web_client_id": "7jae222vlp0ruttq2b0itphqb3",
    "oauth": {}
};


export default awsmobile;
